export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";

export const PURCHASE_ORDER_SUCESS = "PURCHASE_ORDER_SUCESS";
export const PURCHASE_ORDER_FAIL = "PURCHASE_ORDER_FAIL";
