export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const INIT_INGREDIENT = "INIT_INGREDIENT";

export const PURCHASE_BURGER_Loading = "PURCHASE_BURGER_Loading";
export const PURCHASE_ORDER_SUCESS = "PURCHASE_ORDER_SUCESS";
export const PURCHASE_ORDER_FAIL = "PURCHASE_ORDER_FAIL";
export const ORDER_PURCHASED_INIT = "ORDER_PURCHASED_INIT";

// for orders fetching
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_SUCESS = "FETCH_ORDERS_SUCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";
export const FETCH_ORDERS_LOADING = "FETCH_ORDERS_LOADING";

//for auth actions

export const AUTH_START = "AUTH_START";
export const AUTH_START_SUCCESS = "AUTH_START_SUCCESS";
export const AUTH_START_FAIL = "AUTH_START_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
